### PR TITLE
Remove generators in favor or static views.

### PR DESCRIPTION
**Pull request by awong-dev**
Bump the version to 0.3.0 because this is a backwards-incompatible
change.

### CODE REVIEW

**Comment by greggersh** [comment]
Will it ever be the case that an app will want to make slight changes to the header and footer? If so, it may make sense to include generators.

This approach is taken by the devise gem; there's views embedded in the gem, but there's also an option to generate the views and have them written into the app itself as views, allowing the app developer to customize them.

If we can't or don't want to envision this, I'd say this looks good and we have the history in git if we ever want to go back and provide generators.

**Comment by awong-dev** [comment]
Thanks for the review Greg!

Personally, I almost want to constrict the ability of sites to change the pre-determined header/footer.  Always easier to loosen after the fact.

**Comment by emilyville** [comment]
I would like to add the functionality (eventually) to pass things into this and be able to customize a couple elements. Such as: if there is a different notification in the alert bar (as is the case right now for VEC) we could set that somewhere. I'll make this an issue and we can address it later.

**Comment by greggersh** [comment]
There's other options as well, for example, we could define a method or variable to set that would include new/different text, all done via configuration. Best thing to do is to wait until we have a specific feature that we need to implement and address it then (Agile™).

**Comment by emilyville** [comment]
Looks good to me, thanks @awong-dev and @greggersh *

*Agile™ approved.

**Pull request merged**
