### PR TITLE
va_common 0.4.2: 508 compliance

### PR DESCRIPTION
**Pull request by bshyong**
Fixing some contrast issues
Bump up size of search bar and text to be consistent with other apps and comply with 508

### CODE REVIEW

**Comment by bshyong** [comment]
I’m not sure if we need to bump up the gem version / etc. for changes to show up on apps that use the gem.

**Comment by crwallace** [comment]
I think I am passing this review to @webinista since she has done more work with `va_common`.

**Comment by ayaleloehr** [comment]
When changes happen in the gem, the typical procedure has been to bump the gem version, publish the gem update, then change the gem version in each app's Gemfile (GI Bill and VEC).

**Comment by webinista** [comment]
LGTM.

**Pull request merged**
