### PR TITLE
add inspector general to footer and ga global snippet

### PR DESCRIPTION
**Pull request by emilyville**
some updates!

-added ga snippet #4 
-added new footer design and css updates #10

### CODE REVIEW

**Comment by emilyville** [comment]
sending to @dannychapman or @awong-dev or @ayaleloehr for review!

**Comment by emilyville** [comment]
If I get a chance, I'll add in a fix for #11

**Comment by emilyville** [comment]
No dice on #11, but the other improvements should still go out. 

Don't want to hold up for IE9/Windows 7 users as much as they are possibly statistically significant (?)

**Comment by ayaleloehr** [comment]
@emilyville when I changed my local VEC to use this, it made my footer look like this. I feel like the Secretary Bob message shouldn't be that big, right?

screen shot 2016-01-20 at 4 04 00 pm

**Comment by ayaleloehr** [comment]
Deleted prior comment because that was my mistake.  I was mistakenly using files in VEC that were previously copied over to /vendor/va_common folder instead of this gem branch.  I think that type of error is actually why we want this gem though, so that makes me feel somewhat good. 

Looks good to me.

**Pull request merged**
