### PR TITLE
Potentially changing release instructions

### PR DESCRIPTION
**Pull request by ayaleloehr**
@awong-dev thoughts on if this is the right way to release gems?

These instructions are pulled from http://guides.rubygems.org/make-your-own-gem/#your-first-gem

### CODE REVIEW

**Comment by awong-dev** [comment]
This looks roughly right to me.

**Comment by emilyville** [comment]
$ bundle exec rake release does also work! It's shorter, but otherwise apples to apples. 

Otherwise looks good!

**Comment by awong-dev** [comment]
If it works, then we should do `bundle exec rake release` in the instructions. Abstraction layer means we can introduce more steps if necessary later.

**Comment by ayaleloehr** [comment]
You are both correct. Have changed the instructions back to `bundle exec rake release` but leaving this PR because I believe the other context I added around being added as an owner of the gem and creating an account on rubygems.org are still valuable.

**Comment by awong-dev** [comment]
LGTM

Though, we should think about whether or not we should put any instructions for "installing locally".

**Pull request merged**
